---
- name: Setup environment and install packages
  hosts: localhost
  become: yes
  tasks:
    - name: Add Brave Browser repository key
      apt_key:
        url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
        state: present

    - name: Add Brave Browser repository
      apt_repository:
        repo: 'deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main'
        state: present

    - name: Add Google Chrome repository key
      get_url:
        url: https://dl.google.com/linux/linux_signing_key.pub
        dest: /usr/share/keyrings/google-archive-keyring.gpg

    - name: Add Google Chrome repository
      apt_repository:
        repo: 'deb [arch=amd64 signed-by=/usr/share/keyrings/google-archive-keyring.gpg] http://dl.google.com/linux/chrome/deb/ stable main'
        state: present

    - name: Add Insomnia repository key
      apt_key:
        url: https://insomnia.rest/keys/debian-public.key.asc
        state: present

    - name: Add Insomnia repository
      apt_repository:
        repo: 'deb https://dl.bintray.com/getinsomnia/Insomnia /'
        state: present

    - name: Add Sublime Text repository key
      apt_key:
        url: https://download.sublimetext.com/sublimehq-pub.gpg
        state: present

    - name: Add Sublime Text repository
      apt_repository:
        repo: 'deb https://download.sublimetext.com/ apt/stable/'
        state: present

    - name: Add Waterfox repository key
      apt_key:
        url: https://dl.waterfox.net/linux/waterfox.gpg
        state: present

    - name: Add Waterfox repository
      apt_repository:
        repo: 'deb https://dl.waterfox.net/linux/deb/ stable main'
        state: present

    - name: Add Regolith Desktop repository
      apt_repository:
        repo: 'ppa:regolith-linux/release'
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Ensure desired packages are installed
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - arandr
        - brave-browser
        - dbeaver-ce
        - dia
        - discord
        - docker.io
        - ffmpeg
        - gimp
        - google-chrome-stable
        - insomnia
        - mpv
        - obs-studio
        - openssh-client
        - peek
        - python3.12
        - regolith-desktop
        - steam
        - sublime-text
        - waterfox
        - wget
        - wireshark
        - zsh
        - openssh-server # Disable ssh server
