---
- name: Setup environment and install packages
  hosts: localhost
  become: yes
  tasks:
    - name: Add Brave Browser repository key
      apt_key:
        url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
        state: present

    - name: Add Brave Browser repository
      apt_repository:
        repo: 'deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main'
        state: present

    - name: Add Google Chrome repository key
      get_url:
        url: https://dl.google.com/linux/linux_signing_key.pub
        dest: /usr/share/keyrings/google-archive-keyring.gpg

    - name: Add Google Chrome repository
      apt_repository:
        repo: 'deb [arch=amd64 signed-by=/usr/share/keyrings/google-archive-keyring.gpg] http://dl.google.com/linux/chrome/deb/ stable main'
        state: present

    - name: Add Insomnia repository key
      apt_key:
        url: https://insomnia.rest/keys/debian-public.key.asc
        state: present

    - name: Add Insomnia repository
      apt_repository:
        repo: 'deb https://dl.bintray.com/getinsomnia/Insomnia /'
        state: present

    - name: Add Sublime Text repository key
      apt_key:
        url: https://download.sublimetext.com/sublimehq-pub.gpg
        state: present

    - name: Add Sublime Text repository
      apt_repository:
        repo: 'deb https://download.sublimetext.com/ apt/stable/'
        state: present

    # - name: Add Waterfox repository key
    #   apt_key:
    #     url: https://dl.waterfox.net/linux/waterfox.gpg
    #     state: present

    # - name: Add Waterfox repository
    #   apt_repository:
    #     repo: 'deb https://dl.waterfox.net/linux/deb/ stable main'
    #     state: present

    - name: Add Regolith repository key for Focal
      when: ansible_distribution_release == 'focal'
      command: wget -qO - https://regolith-desktop.org/regolith.key | sudo apt-key add -
      changed_when: false

    - name: Add Regolith repository for Focal
      when: ansible_distribution_release == 'focal'
      apt_repository:
        repo: 'deb [arch=amd64] https://regolith-desktop.org/release-3_1-ubuntu-focal-amd64 focal main'
        state: present

    - name: Add Regolith repository key for Mantic
      when: ansible_distribution_release == 'mantic'
      command: wget -qO - https://regolith-desktop.org/regolith.key | gpg --dearmor | sudo tee /usr/share/keyrings/regolith-archive-keyring.gpg > /dev/null
      changed_when: false

    - name: Add Regolith repository for Mantic
      when: ansible_distribution_release == 'mantic'
      apt_repository:
        repo: 'deb [arch=amd64 signed-by=/usr/share/keyrings/regolith-archive-keyring.gpg] https://regolith-desktop.org/release-3_1-ubuntu-mantic-amd64 mantic main'
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Ensure desired packages are installed
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - arandr
        - brave-browser
        - dbeaver-ce
        - dia
        - discord
        - docker.io
        - ffmpeg
        - gimp
        - google-chrome-stable
        - insomnia
        - mpv
        - obs-studio
        - openssh-client
        - peek
        - python3.12
        - regolith-desktop
        - regolith-session-flashback
        - regolith-look-lascaille
        - steam
        - sublime-text
        # - waterfox
        - wget
        - wireshark
        - zsh
        - openssh-server # Disable ssh server
